## Reading in the data

In [50]:
import pandas as pd
from pathlib import Path

file = Path("../data/crop_data_1965_2025.csv")
df = pd.read_csv(file, encoding='utf-8')

df.head(3)

,L�n,Gr�da,Variabel,Tabelluppgift,1965,1966,1967,1968,1969,1970,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,00 Riket,H�stvete,"Areal, hektar",V�rde,.,.,.,.,.,.,...,374380,407570,292530,422160,401170,436330,417760,458750,413830,470840
1,00 Riket,H�stvete,"Totalsk�rd, ton",V�rde,857230,407910,926490,859640,764860,814940,...,2502100,3000000,1399900,3262800,2990200,2877700,3018000,2635900,2708400,3581800
2,00 Riket,V�rvete,"Areal, hektar",V�rde,.,.,.,.,.,.,...,74770,64300,79970,47330,48000,42800,43810,48780,61190,51690

## Renaming some garbled up column names

In [51]:
cols = df.columns.tolist()
cols[0] = "Län"
cols[1] = "Gröda"
df.columns = cols
df.columns

Index(['Län', 'Gröda', 'Variabel', 'Tabelluppgift', '1965', '1966', '1967',
       '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
       '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985',
       '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024', '2025'],
      dtype='str')

## Checking types

In [52]:
df.dtypes

Län              str
Gröda            str
Variabel         str
Tabelluppgift    str
1965             str
                ...
2021             str
2022             str
2023             str
2024             str
2025             str
Length: 65, dtype: object

## Converting numeric columns to floats and creating nulls

In [53]:
cols = df.columns[4:]
df[cols] = df[cols].apply(pd.to_numeric, errors="coerce").astype(float)

##

## Checking for impossible values

In [54]:
df[(df[cols] < 0).any(axis=1)]

Empty DataFrame
Columns: [Län, Gröda, Variabel, Tabelluppgift, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
Index: []

[0 rows x 65 columns]

## Checking unique values

In [55]:
unique_crops = df["Gröda"].unique().tolist()
print(unique_crops)

['H�stvete', 'V�rvete', 'R�g', 'H�stkorn', 'V�rkorn', 'Havre', 'R�gvete', 'H�str�gvete', 'V�rr�gvete', 'Blands�d', 'Majs', 'Spannm�l totalt', '�rter', '�kerb�nor', 'H�straps', 'V�rraps', 'H�strybs', 'V�rrybs', 'Str�s�desgr�dor (exkl. majs) till gr�nfoder', 'Majs till gr�nfoder', 'Andra ett�riga gr�dor till gr�nfoder', 'Oljelin', 'Matpotatis', 'Potatis f�r st�rkelse', 'Sockerbetor', 'Sl�ttervall, f�rsta sk�rd', 'Sl�ttervall, �terv�xt', 'Sl�ttervall, total vallsk�rd']

In [56]:
unique_regions = df["Län"].unique().tolist()
print(unique_regions)

['00 Riket', '01 Stockholms l�n', '03 Uppsala l�n', '04 S�dermanlands l�n', '05 �sterg�tlands l�n', '06 J�nk�pings l�n', '07 Kronobergs l�n', '08 Kalmar l�n', '09 Gotlands l�n', '10 Blekinge l�n', '11 f.d. Kristianstads l�n', '12 Sk�ne l�n', '122 f.d. Malm�hus l�n', '13 Hallands l�n', '14 V�stra G�talands l�n', '141 f.d. G�teborgs o Bohus l�n', '15 f.d. �lvsborgs l�n', '16 f.d. Skaraborgs l�n', '17 V�rmlands l�n', '18 �rebro l�n', '19 V�stmanlands l�n', '20 Dalarnas l�n', '21 G�vleborgs l�n', '22 V�sternorrlands l�n', '23 J�mtlands l�n', '24 V�sterbottens l�n', '25 Norrbottens l�n']

In [57]:
unique_variables = df["Variabel"].unique().tolist()
print(unique_variables)

['Areal, hektar', 'Totalsk�rd, ton']

In [58]:
unique_records = df["Tabelluppgift"].unique().tolist()
print(unique_records)

['V�rde']

## TODO: Convert the strange values